set nocompatible
filetype off

call plug#begin('~/.vim/plugged')

Plug 'junegunn/fzf', { 'do': { -> fzf#install() } }
Plug 'junegunn/fzf.vim'
Plug 'sheerun/vim-polyglot'
Plug 'tpope/vim-eunuch'
Plug 'tpope/vim-surround'
Plug 'tpope/vim-vinegar'

call plug#end()

syntax on
filetype plugin indent on
colorscheme atlas

set autoindent
set backspace=indent,eol,start
set expandtab
set fileformat=unix
set hidden
set hlsearch
set ignorecase
set incsearch
set laststatus=2
set linebreak
set noswapfile
set number
set scrolloff=5
set shiftround
set shiftwidth=3
set shortmess+=I
set showcmd
set showmatch
set smartcase
set smarttab
set softtabstop=3
set splitbelow
set splitright
set tabstop=3
set textwidth=80
set wildignorecase
set wildmenu
set wildmode=list:longest,full

set listchars=tab:·-,trail:_,eol:¬,extends:»,precedes:«
set fillchars=vert:│
set statusline=File\ %F\ %m%r%=[%c\ \|\ %l/%L\ (%p%%)]

if has('mouse')
  set mouse=a
endif

let mapleader = ","
nnoremap <silent> <leader>, :nohlsearch<CR>
nnoremap <silent> <leader>. :set spell!<CR>
nnoremap <silent> <leader>w :set list!<CR>
nnoremap <silent> <leader>p :set paste!<CR>
nnoremap          <leader>r :%s/\<<C-r><C-w>\>//g<Left><Left>
nnoremap <silent> <leader>f :Files<CR>
nnoremap <silent> <leader>b :Buffers<CR>

nnoremap <C-H> <C-W>h
nnoremap <C-J> <C-W>j
nnoremap <C-K> <C-W>k
nnoremap <C-L> <C-W>l
nnoremap Y     y$
nnoremap j     gj
nnoremap k     gk
nnoremap <CR>  o<ESC>

map Q <nop>

augroup _
  autocmd!
  autocmd InsertLeave * set nopaste
augroup END
