" .vimrc
" Author: Nick Platt

set nocompatible
filetype off

set runtimepath+=~/.vim/bundle/Vundle.vim
call vundle#begin('~/.vim/bundle')

Plugin 'VundleVim/Vundle.vim'

Plugin 'Raimondi/delimitMate'
Plugin 'SirVer/ultisnips'
Plugin 'Spaceghost/vim-matchit'
Plugin 'Valloric/YouCompleteMe'
Plugin 'caipre/tabline.vim'
Plugin 'caipre/vim-togglecursor'
Plugin 'chrisbra/vim-diff-enhanced'
Plugin 'ctrlpvim/ctrlp.vim'
Plugin 'derekwyatt/vim-fswitch'
Plugin 'embear/vim-localvimrc'
Plugin 'ervandew/supertab'
Plugin 'fatih/vim-go'
Plugin 'honza/vim-snippets'
Plugin 'junegunn/goyo.vim'
Plugin 'justinmk/vim-sneak'
Plugin 'majutsushi/tagbar'
Plugin 'sheerun/vim-polyglot'
Plugin 'tacahiroy/ctrlp-funky'
Plugin 'tpope/vim-commentary'
Plugin 'tpope/vim-endwise'
Plugin 'tpope/vim-eunuch'
Plugin 'tpope/vim-fugitive'
Plugin 'tpope/vim-obsession'
Plugin 'tpope/vim-surround'
Plugin 'tpope/vim-vinegar'
Plugin 'triglav/vim-visual-increment'

call vundle#end()

syntax on
filetype plugin on
filetype indent on
colorscheme atlas

source $HOME/.vim/functions.vim
source $HOME/.vim/mappings.vim
source $HOME/.vim/options.vim
source $HOME/.vim/plugins.vim

augroup _
   autocmd!

   " Reload .vimrc on write
   autocmd BufWritePost $HOME/.vimrc source $HOME/.vimrc

   " Exit insert mode on idle
   autocmd CursorHoldI * stopinsert
   autocmd InsertEnter * let updaterestore=&updatetime | set updatetime=30000
   autocmd InsertLeave * let &updatetime=updaterestore

   " Remove trailing whitespace on write
   autocmd BufWritePre * :call TrimTrailingWhitespace()
augroup END

let g:mru_tab = 1
nmap <leader>tl :exe "tabn ".g:mru_tab<CR>
autocmd TabLeave * let g:mru_tab = tabpagenr()
