source $HOME/.zsh/aliases.zsh
source $HOME/.zsh/bindkeys.zsh
source $HOME/.zsh/completions.zsh
source $HOME/.zsh/exports.zsh
source $HOME/.zsh/functions.zsh
source $HOME/.zsh/options.zsh
source $HOME/.zsh/prompts.zsh
source $HOME/.zsh/widgets.zsh

zstyle ':completion:*' list-colors "${(@s.:.)LS_COLORS}"
zle_highlight=(isearch:fg=cyan)

eval "$(rbenv init -)"
eval "$(pyenv init -)"
eval "$(pyenv virtualenv-init -)"
