# zshrc
# Author: Nick Platt

source $HOME/.zsh/aliases.zsh
source $HOME/.zsh/bindkeys.zsh
source $HOME/.zsh/colors.zsh
source $HOME/.zsh/completions.zsh
source $HOME/.zsh/exports.zsh
source $HOME/.zsh/functions.zsh
source $HOME/.zsh/options.zsh
source $HOME/.zsh/prompts.zsh
source $HOME/.zsh/widgets.zsh

zstyle ':completion:*' list-colors "${(@s.:.)LS_COLORS}"

# SSH Agent
function agent_active () {
   source "${HOME}/.ssh/agent.${HOST}" &>/dev/null
   ssh-add -l &>/dev/null
}

function agent_status () {
   if agent_active; then
      echo "active"
   elif pidof ssh-agent &>/dev/null; then
      echo "active, no connection"
   else
      echo "inactive"
   fi
}

function agent_start () {
   if agent_active; then return; fi
   (umask 0077; ssh-agent >"${HOME}/.ssh/agent.${HOST}")
   source "${HOME}/.ssh/agent.${HOST}" &>/dev/null
   ssh-add "${HOME}"/.ssh/*-rsa &>/dev/null
   ssh-add "${HOME}"/.ssh/*-ed25519 &>/dev/null
}
agent_active
